# Generated by Django 3.1.3 on 2020-11-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тег')),
                ('url_tags', models.SlugField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('body_post', models.TextField(db_index=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Изображение')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('url', models.SlugField(blank=True, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='post.Tags', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
